version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - pip3 install --upgrade aws-sam-cli
  build:
    commands:
      -FILE=source.zip
          if [ -f "$FILE" ]; then
              unzip $FILE
              echo "$FILE unzipped."
              else 
          echo "$FILE does not exist."
        fi
      - sam build && sam deploy --stack-name $STACK_NAME --s3-bucket $SOURCE_BUCKET_NAME --s3-prefix $SOURCE_BUCKET_PREFIX --region $REGION --no-confirm-changeset --disable-rollback --capabilities CAPABILITY_IAM --parameter-overrides "${parameter_overrides}"